image:
  repository: example.com/placeholder
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

nodeSelector: {}
tolerations: []

resources: {}

ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts: []
  tls: []

# Secret 주입: 둘 중 하나 또는 둘 다 사용 가능
envFromSecrets: [] # ["frontend-dev-app"]처럼 Secret 이름
env: {} # 예: BACKEND_API_URL: {secretName: "...", key: "BACKEND_API_URL"}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts: []
  tls: []
