apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/ORG/project-hybrid_frontend_gitops
    targetRevision: main
    path: environments/prod/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
