image:
  repository: "<ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/next-fe"
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

nodeSelector: {}
tolerations: []
resources: {}

ingress:
  enabled: true
  className: alb
  annotations: {}
  hosts: []
  tls: []
